Repository WildCodeSchool/2023-03-JS-TLSE-P3-Externatic, pull requests merged in 2023-07, with the labels that each got.

#8 Fixed responsive for pres
  frontend/src/css/pages/Connexion.css
  frontend/src/css/pages/MyProfile.css
  frontend/src/pages/MyProfile.jsx
  package-lock.json
Labels: Reviewed, Corrections done

#12 S02 us02 1 admin my profile
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/images/admin-connexion.png
  frontend/src/assets/images/login-page.png
  frontend/src/components/ConnexionLinks.jsx
  frontend/src/components/FormularConnexion.jsx
  frontend/src/components/MainNavBar.jsx
  frontend/src/contexts/ConnexionContext.jsx
  frontend/src/contexts/TokenContext.jsx
  frontend/src/css/components/ConnexionLinks.css
  frontend/src/css/components/FormularConnexion.css
  frontend/src/css/components/MainNavBar.css
  frontend/src/css/pages/AdminConnexion.css
  frontend/src/css/pages/Connexion.css
  frontend/src/css/pages/MyProfile.css
  frontend/src/pages/AdminConnexion.jsx
  frontend/src/pages/Connexion.jsx
  frontend/src/pages/MyProfile.jsx
  frontend/src/pages/Offers.jsx
  frontend/src/pages/admins/UsersManagement.jsx
  frontend/src/utils/ValidationConnexion.jsx
Labels: Reviewed

#13 S02 us01 2 connection
  backend/.env.sample
  backend/database.sql
  backend/package-lock.json
  backend/package.json
  backend/src/controllers/AdminController.js
  backend/src/controllers/ApplicantController.js
  backend/src/controllers/CompanyController.js
  backend/src/controllers/UserController.js
  backend/src/controllers/itemControllers.js
  backend/src/models/AbstractManager.js
  backend/src/models/AdminManager.js
  backend/src/models/ApplicantManager.js
  backend/src/models/CompanyManager.js
  backend/src/models/ItemManager.js
  backend/src/models/index.js
  backend/src/router.js
  backend/src/services/auth.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/OfferCardList.jsx
  frontend/src/css/components/OfferCardList.css
  frontend/src/pages/Home.jsx
  package-lock.json
  package.json
Labels: Reviewed, Corrections done

#14 Harmonizing elements
  frontend/src/App.css
  frontend/src/components/FormularConnexion.jsx
  frontend/src/css/pages/AdminConnexion.css
  frontend/src/css/pages/MyProfile.css
  frontend/src/pages/Connexion.jsx
  frontend/src/pages/MyProfile.jsx
Labels: Reviewed

#15 S02 us01 2 bis connexion database
  backend/database.sql
Labels: Reviewed

#17 S03 us03 1 offers unfiltered
  backend/src/controllers/CategoryController.js
  backend/src/controllers/ContractController.js
  backend/src/controllers/OfferController.js
  backend/src/models/CategoryManager.js
  backend/src/models/ContractManager.js
  backend/src/models/OfferManager.js
  backend/src/models/index.js
  backend/src/router.js
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/icons/white_heart.svg
  frontend/src/components/MainNavBar.jsx
  frontend/src/css/components/Footer.css
  frontend/src/css/components/MainNavBar.css
  frontend/src/css/components/SecondaryNavBar.css
  frontend/src/css/pages/Connexion.css
  frontend/src/pages/Offers.jsx
Labels: Reviewed

#19 S02 us00 1 main nav bar
  backend/src/controllers/UserController.js
  frontend/src/components/MainNavBar.jsx
  frontend/src/components/SecondaryNavBar.jsx
  frontend/src/contexts/TokenContext.jsx
  frontend/src/css/components/SecondaryNavBar.css
  frontend/src/pages/Connexion.jsx
Labels: Reviewed

#20 S03 us03 2 offer card
  frontend/src/App.jsx
  frontend/src/assets/icons/black_heart.svg
  frontend/src/assets/icons/black_heart_fill.svg
  frontend/src/assets/icons/person_white.svg
  frontend/src/assets/icons/white_heart_empty.svg
  frontend/src/assets/icons/white_heart_fill.svg
  frontend/src/assets/images/data_collection.png
  frontend/src/components/OfferCardLarge.jsx
  frontend/src/components/OfferCardList.jsx
  frontend/src/css/components/OfferCardList.css
  frontend/src/pages/Home.jsx
  frontend/src/pages/Offers.jsx
Labels: Reviewed

#21 Dev
  backend/src/controllers/UserController.js
  frontend/src/App.jsx
  frontend/src/assets/icons/black_heart.svg
  frontend/src/assets/icons/black_heart_fill.svg
  frontend/src/assets/icons/person_white.svg
  frontend/src/assets/icons/white_heart_empty.svg
  frontend/src/assets/icons/white_heart_fill.svg
  frontend/src/assets/images/data_collection.png
  frontend/src/components/MainNavBar.jsx
  frontend/src/components/OfferCardLarge.jsx
  frontend/src/components/OfferCardList.jsx
  frontend/src/components/SecondaryNavBar.jsx
  frontend/src/contexts/TokenContext.jsx
  frontend/src/css/components/OfferCardList.css
  frontend/src/css/components/SecondaryNavBar.css
  frontend/src/pages/Connexion.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/Offers.jsx
Labels: Reviewed

#22 S02 us01 1 unique page connection
  frontend/src/css/pages/Connexion.css
  frontend/src/pages/Connexion.jsx
  frontend/src/utils/ValidationConnexion.jsx
Labels: Reviewed

#23 manage error login adding a state
  frontend/src/css/pages/Connexion.css
  frontend/src/pages/Connexion.jsx
Labels: Reviewed

#24 S03 us03 1 offers unfiltered
  backend/src/controllers/OfferController.js
  backend/src/models/OfferManager.js
  backend/src/router.js
  backend/src/services/auth.js
  frontend/src/App.jsx
  frontend/src/css/components/OfferCardList.css
  frontend/src/css/pages/Offers.css
  frontend/src/pages/Connexion.jsx
  frontend/src/pages/MyProfile.jsx
  frontend/src/pages/Offers.jsx
Labels: Changes requested

#25 S03 us03 3 offer modal
  backend/database.sql
  backend/src/controllers/OfferController.js
  backend/src/models/OfferManager.js
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/assets/icons/black_city_fill.svg
  frontend/src/assets/icons/contract_black.svg
  frontend/src/assets/icons/contract_white.svg
  frontend/src/assets/icons/rocket_pink.svg
  frontend/src/assets/icons/tools_pink.svg
  frontend/src/assets/icons/white_city_fill.svg
  frontend/src/components/OfferCardList.jsx
  frontend/src/components/OfferModal.jsx
  frontend/src/css/components/OfferModal.css
  frontend/src/pages/Offers.jsx
Labels: Reviewed

#27 S04 us41 user management
  backend/src/controllers/AdminController.js
  backend/src/controllers/ApplicantController.js
  backend/src/controllers/CompanyController.js
  backend/src/controllers/OfferController.js
  backend/src/models/OfferManager.js
  backend/src/router.js
  backend/src/services/auth.js
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/css/pages/UsersManagement.css
  frontend/src/pages/Offers.jsx
  frontend/src/pages/admins/UsersManagement.jsx
Labels: Reviewed

#26 Us06 s04 1 subscribe page frontend route post
  frontend/src/App.jsx
  frontend/src/assets/icons/company_black.svg
  frontend/src/assets/icons/company_building_black.svg
  frontend/src/assets/icons/company_id_black.svg
  frontend/src/assets/icons/number_black.svg
  frontend/src/components/FormNewApplicant.jsx
  frontend/src/components/FormNewCompany.jsx
  frontend/src/components/LinkLogInSubscribe.jsx
  frontend/src/contexts/TokenContext.jsx
  frontend/src/contexts/ValidationFormContext.jsx
  frontend/src/css/components/FormNewUser.css
  frontend/src/css/components/LinkLogInSubscribe.css
  frontend/src/css/pages/Connexion.css
  frontend/src/css/pages/Subscribe.css
  frontend/src/pages/Connexion.jsx
  frontend/src/pages/Subscribe.jsx
  frontend/src/utils/ValidationConnexion.jsx
Labels: Reviewed

#30 Dev
  frontend/src/App.jsx
  frontend/src/assets/icons/company_black.svg
  frontend/src/assets/icons/company_building_black.svg
  frontend/src/assets/icons/company_id_black.svg
  frontend/src/assets/icons/number_black.svg
  frontend/src/components/FormNewApplicant.jsx
  frontend/src/components/FormNewCompany.jsx
  frontend/src/components/LinkLogInSubscribe.jsx
  frontend/src/contexts/TokenContext.jsx
  frontend/src/contexts/ValidationFormContext.jsx
  frontend/src/css/components/FormNewUser.css
  frontend/src/css/components/LinkLogInSubscribe.css
  frontend/src/css/pages/Connexion.css
  frontend/src/css/pages/Subscribe.css
  frontend/src/pages/Connexion.jsx
  frontend/src/pages/Subscribe.jsx
  frontend/src/utils/ValidationConnexion.jsx
Labels: Reviewed

#32 Fix bugs
  frontend/src/App.css
  frontend/src/css/pages/Connexion.css
  frontend/src/css/pages/Subscribe.css
  frontend/src/pages/Connexion.jsx
Labels: Reviewed

#33 Dev to main for the pres :)
  frontend/src/App.css
  frontend/src/css/pages/Connexion.css
  frontend/src/css/pages/Subscribe.css
  frontend/src/pages/Connexion.jsx
Labels: Reviewed

#34 S03_US03-2_offer_card: add large card and style of the offer modal mo…
  backend/src/models/OfferManager.js
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/icons/person_black.svg
  frontend/src/assets/icons/person_white.svg
  frontend/src/components/OfferCardLarge.jsx
  frontend/src/components/OfferModal.jsx
  frontend/src/css/components/FormNewUser.css
  frontend/src/css/components/LinkLogInSubscribe.css
  frontend/src/css/components/OfferModal.css
  frontend/src/css/pages/Connexion.css
  frontend/src/css/pages/Home.css
  frontend/src/css/pages/Subscribe.css
  frontend/src/pages/Home.jsx
Labels: Reviewed

#35 S04 us42 category management
  backend/src/controllers/AdminController.js
  backend/src/controllers/CategoryController.js
  backend/src/controllers/ContractController.js
  backend/src/models/CategoryManager.js
  backend/src/models/ContractManager.js
  backend/src/router.js
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/OfferCardManagement.jsx
  frontend/src/components/SecondaryNavBar.jsx
  frontend/src/contexts/FiltersContext.jsx
  frontend/src/contexts/TokenContext.jsx
  frontend/src/css/components/OfferCardList.css
  frontend/src/css/pages/FieldsManagement.css
  frontend/src/css/pages/MyProfile.css
  frontend/src/pages/Offers.jsx
  frontend/src/pages/admins/FieldsManagement.jsx
  frontend/src/pages/admins/OffersManagement.jsx
Labels: Corrections done

#37 Us06 s04 5 subscribe page frontend adding alert
  frontend/package-lock.json
  frontend/package.json
  frontend/src/components/FormNewApplicant.jsx
  frontend/src/components/FormNewCompany.jsx
  frontend/src/components/LinkLogInSubscribe.jsx
  frontend/src/contexts/ValidationFormContext.jsx
  frontend/src/css/components/FormNewUser.css
  frontend/src/css/components/SwalModal.css
  frontend/src/css/pages/Connexion.css
  frontend/src/pages/Connexion.jsx
  frontend/src/pages/Subscribe.jsx
Labels: Reviewed

#38 Add swal popup
  frontend/src/App.jsx
  frontend/src/css/components/CustomStyleSwal.css
  frontend/src/css/components/SwalModal.css
  frontend/src/pages/admins/UsersManagement.jsx
Labels: Reviewed

#39 S05 us29 company show offers
  backend/src/controllers/OfferController.js
  backend/src/models/OfferManager.js
  backend/src/router.js
  backend/src/services/auth.js
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/contexts/TokenContext.jsx
  frontend/src/css/pages/MyPublishedOffers.css
  frontend/src/pages/admins/FieldsManagement.jsx
  frontend/src/pages/admins/OffersManagement.jsx
  frontend/src/pages/admins/UsersManagement.jsx
  frontend/src/pages/companies/MyPublishedOffers.jsx
Labels: Reviewed

#43 big big error in the components FormNewApplicant and FormNewCompany r…
  frontend/src/components/FormNewApplicant.jsx
Labels: Reviewed

#44 S04 us17 applicant dashboard favorite
  backend/src/controllers/AdminController.js
  backend/src/controllers/ApplicantController.js
  backend/src/controllers/FavoriteController.js
  backend/src/models/FavoriteManager.js
  backend/src/models/index.js
  backend/src/router.js
  backend/src/services/auth.js
  frontend/src/assets/icons/black_heart_empty.svg
  frontend/src/assets/icons/black_heart_fill.svg
  frontend/src/assets/icons/white_heart_empty.svg
  frontend/src/assets/icons/white_heart_fill.svg
  frontend/src/components/OfferCardList.jsx
  frontend/src/components/OfferModal.jsx
  frontend/src/contexts/TokenContext.jsx
  frontend/src/css/components/OfferCardList.css
  frontend/src/css/components/OfferModal.css
  frontend/src/pages/Offers.jsx
  frontend/src/pages/applicants/MyFavoritesOffers.jsx
Labels: Reviewed

#45 S02 us02 1 admin my profile
  backend/database.sql
  backend/src/controllers/AdminController.js
  backend/src/controllers/ApplicantController.js
  backend/src/controllers/CompanyController.js
  backend/src/controllers/OfferController.js
  backend/src/controllers/UserController.js
  backend/src/models/AbstractManager.js
  backend/src/models/AdminManager.js
  backend/src/models/ApplicantManager.js
  backend/src/models/CompanyManager.js
  backend/src/models/OfferManager.js
  backend/src/router.js
  backend/src/services/auth.js
  frontend/src/App.css
  frontend/src/components/AdminForm.jsx
  frontend/src/components/ApplicantForm.jsx
  frontend/src/components/CompanyForm.jsx
  frontend/src/components/FormNewApplicant.jsx
  frontend/src/css/pages/MyProfile.css
  frontend/src/pages/MyProfile.jsx
  frontend/src/pages/admins/UsersManagement.jsx
  package-lock.json
  package.json
Labels: Reviewed

#46 S05 us05 3 home personalize message
  backend/src/controllers/UserController.js
  backend/src/router.js
  frontend/src/App.jsx
  frontend/src/assets/icons/externatic-hello.svg
  frontend/src/assets/icons/externatic-sablier.svg
  frontend/src/assets/images/header_image.svg
  frontend/src/components/FormNewCompany.jsx
  frontend/src/components/InputSearch.jsx
  frontend/src/contexts/TokenContext.jsx
  frontend/src/css/components/CustomStyleSwal.css
  frontend/src/css/pages/Home.css
  frontend/src/pages/Connexion.jsx
  frontend/src/pages/Home.jsx
Labels: Reviewed

#47 S03 us03 2 offer card
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.jsx
  frontend/src/components/OfferCardCarousel.jsx
  frontend/src/components/OfferCardLarge.jsx
  frontend/src/components/OfferCardList.jsx
  frontend/src/components/OfferModal.jsx
  frontend/src/css/components/OfferCardCarousel.css
  frontend/src/css/components/OfferCardList.css
  frontend/src/css/components/OfferModal.css
  frontend/src/css/pages/Home.css
  frontend/src/pages/Home.jsx
Labels: Reviewed

#49 S05 us17 fix style
  backend/database.sql
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/images/loading.png
  frontend/src/assets/images/no_data.png
  frontend/src/assets/images/unauthorized_error401.png
  frontend/src/components/Error401Unauthorized.jsx
  frontend/src/components/Error404.jsx
  frontend/src/components/ErrorNoData.jsx
  frontend/src/components/IsLoading.jsx
  frontend/src/components/OfferCardCarousel.jsx
  frontend/src/components/OfferCardLarge.jsx
  frontend/src/components/OfferCardList.jsx
  frontend/src/components/OfferModal.jsx
  frontend/src/contexts/MessagesErrorContext.jsx
  frontend/src/css/components/Error.css
  frontend/src/css/components/OfferCardCarousel.css
  frontend/src/css/components/OfferCardList.css
  frontend/src/css/components/OfferModal.css
  frontend/src/pages/Offers.jsx
  frontend/src/pages/admins/FieldsManagement.jsx
  frontend/src/pages/admins/OffersManagement.jsx
  frontend/src/pages/admins/UsersManagement.jsx
  frontend/src/pages/applicants/MyFavoritesOffers.jsx
Labels: Reviewed

#51 S05 data validation myprofile
  backend/database.sql
  backend/src/controllers/AdminController.js
  backend/src/controllers/ApplicantController.js
  backend/src/controllers/CompanyController.js
  backend/src/controllers/UserController.js
  backend/src/router.js
  frontend/src/components/CompanyForm.jsx
Labels: Reviewed

#54 S05 data validation myprofile
  backend/src/models/OfferManager.js
  frontend/src/pages/Offers.jsx
Labels: Reviewed

#55 S05 us17 fix style
  backend/src/controllers/ApplicantController.js
  frontend/src/App.css
  frontend/src/components/MainNavBar.jsx
  frontend/src/components/OfferCardLarge.jsx
  frontend/src/components/OfferCardList.jsx
  frontend/src/components/OfferModalManagement.jsx
  frontend/src/contexts/MessagesErrorContext.jsx
  frontend/src/css/components/OfferModal.css
  frontend/src/css/components/SecondaryNavBar.css
  frontend/src/css/pages/Home.css
  frontend/src/css/pages/MyProfile.css
  frontend/src/pages/admins/FieldsManagement.jsx
  frontend/src/pages/admins/OffersManagement.jsx
  frontend/src/pages/companies/MyPublishedOffers.jsx
Labels: Reviewed

#56 S05_US17-Fix_Style: toast modified
  frontend/src/components/OfferCardLarge.jsx
  frontend/src/components/OfferCardList.jsx
Labels: Reviewed

#57 S05 data validation myprofile
  backend/src/controllers/ApplicantController.js
  backend/src/controllers/CompanyController.js
  backend/src/controllers/UserController.js
Labels: Reviewed

#59 S06 fix details
  frontend/src/App.css
  frontend/src/components/FormNewApplicant.jsx
  frontend/src/components/OfferCardManagement.jsx
  frontend/src/css/components/CustomStyleSwal.css
  frontend/src/css/components/Footer.css
  frontend/src/css/components/FormNewUser.css
  frontend/src/css/pages/Home.css
  frontend/src/pages/admins/FieldsManagement.jsx
Labels: Reviewed

#60 S05_US17-Fix_Style: fix footer, page not exist
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/contexts/MessagesErrorContext.jsx
  frontend/src/css/components/Footer.css
  frontend/src/css/components/FormNewUser.css
  frontend/src/css/components/MainNavBar.css
  frontend/src/css/pages/Connexion.css
  frontend/src/css/pages/Subscribe.css
  frontend/src/pages/NotFound.jsx
Labels: Reviewed

#62 Fixed showed modal company that the company name didn't show
  backend/src/models/OfferManager.js
  frontend/src/components/MainNavBar.jsx
Labels: Reviewed

#63 toggle password visibility
  backend/src/controllers/AdminController.js
  backend/src/services/auth.js
  frontend/src/App.jsx
  frontend/src/assets/icons/eye_closed.svg
  frontend/src/assets/icons/eye_open.svg
  frontend/src/components/AdminForm.jsx
  frontend/src/components/ApplicantForm.jsx
  frontend/src/components/CompanyForm.jsx
  frontend/src/components/FormNewApplicant.jsx
  frontend/src/components/FormNewCompany.jsx
  frontend/src/components/ToggleConfirmedPasswordVisibility.jsx
  frontend/src/components/ToggleNewPasswordVisibility.jsx
  frontend/src/components/TogglePasswordVisibility.jsx
  frontend/src/contexts/PasswordVisibilityContext.jsx
  frontend/src/css/components/TogglePasswordVisibility.css
  frontend/src/pages/Connexion.jsx
  frontend/src/pages/Subscribe.jsx
Labels: Reviewed

#64 S05 us17 fix style
  frontend/src/assets/icons/black_icons_plus.svg
  frontend/src/assets/icons/pink_star.svg
  frontend/src/components/OfferModal.jsx
  frontend/src/components/OfferModalManagement.jsx
  frontend/src/css/components/TogglePasswordVisibility.css
  frontend/src/css/pages/FieldsManagement.css
  frontend/src/css/pages/UsersManagement.css
  frontend/src/pages/admins/FieldsManagement.jsx
  frontend/src/pages/admins/UsersManagement.jsx
Labels: Reviewed

#65 Dev
  backend/src/controllers/AdminController.js
  backend/src/models/OfferManager.js
  backend/src/services/auth.js
  frontend/src/App.jsx
  frontend/src/assets/icons/black_icons_plus.svg
  frontend/src/assets/icons/eye_closed.svg
  frontend/src/assets/icons/eye_open.svg
  frontend/src/assets/icons/pink_star.svg
  frontend/src/components/AdminForm.jsx
  frontend/src/components/ApplicantForm.jsx
  frontend/src/components/CompanyForm.jsx
  frontend/src/components/FormNewApplicant.jsx
  frontend/src/components/FormNewCompany.jsx
  frontend/src/components/MainNavBar.jsx
  frontend/src/components/OfferModal.jsx
  frontend/src/components/OfferModalManagement.jsx
  frontend/src/components/ToggleConfirmedPasswordVisibility.jsx
  frontend/src/components/ToggleNewPasswordVisibility.jsx
  frontend/src/components/TogglePasswordVisibility.jsx
  frontend/src/contexts/PasswordVisibilityContext.jsx
  frontend/src/css/components/TogglePasswordVisibility.css
  frontend/src/css/pages/FieldsManagement.css
  frontend/src/css/pages/UsersManagement.css
  frontend/src/pages/Connexion.jsx
  frontend/src/pages/Subscribe.jsx
  frontend/src/pages/admins/FieldsManagement.jsx
  frontend/src/pages/admins/UsersManagement.jsx
Labels: Reviewed

#66 S05 hotfixes
  frontend/src/components/OfferCardManagement.jsx
Labels: Reviewed

#67 Dev
  frontend/src/components/OfferCardManagement.jsx
Labels: Reviewed
